[package]
name = "watchdog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = "0.2.0"
thiserror = "1.0.31"
chrono = "0.4.23"

[dev-dependencies]
tokio-test = "0.4.2"
